name: Update news

on:
  schedule:
    - cron: "*/30 * * * *"   # 30분마다(UTC 기준)
  workflow_dispatch: {}       # 필요 시 수동 실행 버튼

concurrency:
  group: update-news
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # news.json 커밋/푸시에 필요

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Build news.json
        run: npm run fetch

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain docs/data/news.json)" ]; then
            git add docs/data/news.json
            git commit -m "chore: update news.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
